# Generated by Django 5.0.1 on 2024-07-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_category_alter_document_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
